name: google_maps_atlas_example
description: Google maps atlas example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  atlas: 0.12.2
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  google_maps_atlas:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
